githubRepoOwner: drosi94
githubRepoName: test-spr
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: true
requireApproval: false
branchNameIncludeTarget: true
showPrTitlesInStack: false
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
branchPushIndividually: false